Remove unused import
pep8 runtests: commands[0] | flake8 .
./cinder/tests/tempest/api/volume/test_volume_unicode.py:20:1: F401 'test_utils' imported but unused
ERROR: InvocationError for command '/opt/stack/cinder/.tox/pep8/bin/flake8 .' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed